### ISSUE TITLE
Need Info: Possble to use the script with Comfort Control Panel

### ISSUE THREAD

**Issue by maderflo** [csreades/AutothermDieselRepeater#1]
Hey thank for the Work! Do you know if its posstible to use the Script with the Comfort Control Panel?

Thanks in advance!

**Comment by csreades** [comment]
I cannot say for certain as I do not have one but I would say it will. The
controller only sends some basic commands really and the heater does the
work. Therefore unless you have to “upgrade” the heater the controllers
should all work the same.
